ism=input("Iltimos ismingizni kiriting!\n>>>")
familya=input("Iltimos familyangizni kiriting!\n>>>")
ota_ism=input("Iltimos otangizni ismini kiriting!\n>>>")
print(f"Sizning ismingiz {ism.title()}, familyangiz {familya.title()}, otangizni ismi {ota_ism.title()} ekan!")
a=input("To'g'ri topdimmi?\n>>>")